### ISSUE TITLE
Check running on Windows/Linux

### ISSUE THREAD

**Issue by dmntk** [dmntk/dmntk.java.server#5]
Check if the released version 0.1.0 properly runs on Windows and Linux with Java 17 installed.

Run:
```
java -jar server-0.1.0.jar
```
Check:
```
http://127.0.0.1:22023/api/rest/v1/system/info
```
Expected result:
```
{"data":{"name":"Java RPC server for DMNTK","version":"0.1.0"}}
```

**Comment by PyszM** [comment]
![obraz](https://github.com/dmntk/dmntk.java.server/assets/73468031/c1ea7989-9f4a-47f3-a55a-d57595d3cec5)
Works on Windows 8.1 and Java 17.0.7

**Comment by dmntk** [comment]
Many thanks for your help!
